# Las matematicas tras la regresion logistica

## Las tablas de contigencia

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../datasets/gender-purchase/Gender Purchase.csv")
df.head()

   Gender Purchase
0  Female      Yes
1  Female      Yes
2  Female       No
3    Male       No
4    Male      Yes

In [5]:
df.shape

(511, 2)

In [6]:
contingency_table = pd.crosstab(df["Gender"], df["Purchase"])
contingency_table

Purchase   No  Yes
Gender
Female    106  159
Male      125  121

In [7]:
contingency_table.sum(axis = 1)

Gender
Female    265
Male      246
dtype: int64

In [8]:
contingency_table.sum(axis = 0)

Purchase
No     231
Yes    280
dtype: int64

In [9]:
contingency_table.astype("float").div(contingency_table.sum(axis = 1), axis = 0)

Purchase       No      Yes
Gender
Female    0.40000  0.60000
Male      0.50813  0.49187

## Probabilidad condicional

In [10]:
from IPython.display import display, Math, Latex

* Cual es la probabilidad de que un cliente compre un producto sabiendo que es un hombre?
* Cual es la probabilidad de que sabiendo que un cliente compra un producto sea mujer?

In [21]:
display(Math(r'P(Purchase|Male) = \frac{Numero\ total\ de\ compras\ hechas\ por\ hombres}{Numero\ total\ de\ hombres\ del\ grupo} = \frac{Purchase\cap Male}{Male}'))
121/246

0.491869918699187

In [19]:
display(Math(r'P(No\ Purchase|Male) = 1-P(Purchase|Male)'))
1-121/246

0.5081300813008129

In [22]:
display(Math(r'P(Female|Purchase) = \frac{Numero\ total\ de\ compras\ hechas\ por\ mujeres}{Numero\ total\ de\ compras} = \frac{Female\cap Purchase}{Purchase}'))
159/280

0.5678571428571428

In [23]:
display(Math(r'P(Male|Purchase)'))
121/280

0.43214285714285716

In [26]:
display(Math(r'P(Male|Purchase)'))
print(121/246)
display(Math(r'P(No\ Purchase|Male'))
print(125/246)
display(Math(r'P(Female|Purchase'))
print(159/265)
display(Math(r'P(No\ Purchase|Female'))
print(106/265)

0.491869918699187

0.508130081300813

0.6

0.4

## Ratio de probabilidades
Cociente entre los casos de exito sobre los de fracaso en el suceso estudiado y para cada grupo

In [38]:
display(Math(r'P_m = \ probabilidad\ de\ compra\ sabiendo\ que\ es\ un\ hombre'))

display(Math(r'P_f = \ probabilidad\ de\ compra\ sabiendo\ que\ es\ una\ mujer'))

display(Math(r'odds\in[0,+\infty]'))

display(Math(r'odds_{purchase,male} = \frac{P_m}{1-P_m} = \frac{N_{p,m}}{N_{\bar p, m}}'))

display(Math(r'odds_{purcharse,female} = \frac{P_f}{1-P_f} = \frac{N_{p,f}}{N_{\bar p, f}}'))

In [31]:
pm = 121/246
pf = 159/265
odds_m = pm / (1-pm) # 121/125
odds_f = pf / (1-pf) # 159/106

In [32]:
odds_m

0.9680000000000002

In [33]:
odds_f

1.4999999999999998

* Si el ratio es superior a 1, es mas probable el exito que el fracaso. Cuanto mayor es el ratio, mas probabilidad de exito en nuestro suceso.
* Si el ratio es exactamente igual a 1, exito y fracaso son equiprobables (p=0.5)
* Si el ratio es menor que 1, el fracaso es mas probable que el exito. Cuanto menor es el ratio, menor es la probabilidad de exito en nuestro suceso.

In [39]:
display(Math(r'odds_{ratio} = \frac{odds_{purchase,male}}{odds_{purchase,female}}'))

In [41]:
odds_r = odds_m/odds_f

In [42]:
odds_r

0.6453333333333335

In [44]:
1/odds_r # odds_f/odds_m

1.5495867768595037

## La regresion logistica desde la regresion lineal

In [46]:
display(Math(r'y = \alpha + \beta \cdot x'))
display(Math(r'(x,y)\in[-\infty, +\infty]^2'))

In [61]:
display(Math(r'Y\in\{0,1\}??'))
display(Math(r'P\in [0,1]'))
display(Math(r'X\in[-\infty, +\infty]'))
display(Math(r'P = \alpha + \beta\cdot X'))

P es la probabilidad condicionada de exito o de fracaso condicionada a la presencia de la variable X

In [54]:
display(Math(r'\frac{P}{1-P}= \alpha + \beta\cdot X\in [0,+\infty]'))

In [55]:
display(Math(r'ln(\frac{P}{1-P}) = \alpha + \beta\cdot X'))

In [60]:
display(Math(r'\begin{cases}\frac{P}{1-P}\in[0,1]\Rightarrow ln(\frac{P}{1-P})\in[-\infty,0]\\ \frac{P}{1-P}\in[1,+\infty]\Rightarrow ln(\frac{P}{1-P})\in[0, \infty]\end{cases}'))

In [68]:
display(Math(r'ln(\frac{P}{1-P}) = \alpha + \beta\cdot X'))
display(Math(r'\frac{P}{1-P} = e^{\alpha + \beta\cdot X}'))
display(Math(r'P = \frac{e^{\alpha+\beta\cdot X}}{1+e^{\alpha+\beta\cdot X}}'))
display(Math(r'P = \frac{1}{1+e^{-(\alpha+\beta\cdot X)}}'))

* Si a+bX es muy pequeño (negativo), entonces P tiende a 0
* Si a+bX es 0, P = 0.5
* Si a+bX es muy grande (positivo), entonces P tiende a 1

### Regresion logistica multiple

In [69]:
display(Math(r'P = \frac{1}{1+e^{-(\alpha+\sum_{i=1}^n\beta_i\cdot X)}}'))

In [71]:
display(Math(r'\vec\beta = (\beta_1,\beta_2,\cdots,\beta_n)'))
display(Math(r'\vec{X} = (x_1,x_2,\cdots,x_n)'))
display(Math(r'P = \frac{1}{1+e^{-(\alpha+\vec\beta_i\cdot \vec{X})}}'))