# K Nearest Neighbors

In [20]:
import numpy as np
from sklearn import preprocessing, neighbors
from sklearn.model_selection import train_test_split
import pandas as pd

In [45]:
df = pd.read_csv("../datasets/cancer/breast-cancer-wisconsin.data.txt", header=None)
df.head()

        0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [9]:
df.describe()

                 0           1           2           3   ...          7           8           9           10
count  6.990000e+02  699.000000  699.000000  699.000000  ...  699.000000  699.000000  699.000000  699.000000
mean   1.071704e+06    4.417740    3.134478    3.207439  ...    3.437768    2.866953    1.589413    2.689557
std    6.170957e+05    2.815741    3.051459    2.971913  ...    2.438364    3.053634    1.715078    0.951273
min    6.163400e+04    1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000    2.000000
25%    8.706885e+05    2.000000    1.000000    1.000000  ...    2.000000    1.000000    1.000000    2.000000
50%    1.171710e+06    4.000000    1.000000    1.000000  ...    3.000000    1.000000    1.000000    2.000000
75%    1.238298e+06    6.000000    5.000000    5.000000  ...    5.000000    4.000000    1.000000    4.000000
max    1.345435e+07   10.000000   10.000000   10.000000  ...   10.000000   10.000000   10.000000    4.000000

[8 rows x 10 columns]

In [46]:
df.columns = ["name", "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "class"]

In [47]:
df.head()

      name  V1  V2  V3  V4  V5  V6  V7  V8  V9  class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2

In [48]:
df = df.drop(columns=["name"])

In [49]:
df.replace("?", -99999, inplace=True)

In [50]:
Y = df["class"]

In [51]:
X = df[["V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]]

In [52]:
X.head()

   V1  V2  V3  V4  V5  V6  V7  V8  V9
0   5   1   1   1   2   1   3   1   1
1   5   4   4   5   7  10   3   2   1
2   3   1   1   1   2   2   3   1   1
3   6   8   8   1   3   4   3   7   1
4   4   1   1   3   2   1   3   1   1

In [53]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int64

## Clasificador de los K vecinos

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [55]:
clf = neighbors.KNeighborsClassifier()

In [56]:
clf.fit(X_train, Y_train)

KNeighborsClassifier()

In [57]:
accuracy = clf.score(X_test, Y_test)
accuracy

0.95

# Clasificacion sin limpieza

In [41]:
df = pd.read_csv("../datasets/cancer/breast-cancer-wisconsin.data.txt", header=None)
df.replace("?", -99999, inplace=True)
df.columns = ["name", "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "class"]

Y = df["class"]
X = df[["name","V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, Y_train)

accuracy = clf.score(X_test, Y_test)
accuracy

0.6071428571428571

# Clasificar nuevos datos

In [58]:
sample_measure = np.array([4,2,1,1,1,2,3,2,1])

In [59]:
sample_measure = sample_measure.reshape(1,-1)

In [60]:
predict = clf.predict(sample_measure)

C:\Users\progr\anaconda3\envs\ml-curso\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [61]:
predict

array([2])

In [62]:
sample_measure2 = np.array([[4,2,1,1,1,2,3,2,1], [4,2,1,1,1,2,3,2,1]]).reshape(2,-1)

In [63]:
predict = clf.predict(sample_measure2)

C:\Users\progr\anaconda3\envs\ml-curso\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [64]:
predict

array([2, 2])